version: '{build}'
skip_tags: true
clone_depth: 10
branches:
  only:
    - master
  except:
    - gh-pages
os: Windows Server 2012
environment:
  matrix:
    - ruby_version: "25-x64"
install:
  - ps: |
      $Env:PATH = "C:\Ruby${Env:ruby_version}\bin;${Env:PATH}"
  - bundle config --local path vendor/bundle
  - ruby -v
  - bundle -v
build_script:
  - bundle update
  - bundle install
test_script:
  - bundle exec rake --quiet
cache:
  - vendor/bundle
